# Generated by Django 6.0.4 on 2026-04-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('organic', 'Orgânico')], default='organic', max_length=20)),
                ('raw_context', models.TextField(blank=True)),
                ('base_title', models.CharField(blank=True, max_length=180)),
                ('base_caption', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=180)),
                ('hashtags', models.TextField(blank=True)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('generation_status', models.CharField(default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Post base',
                'verbose_name_plural': 'Posts base',
                'ordering': ['-created_at'],
            },
        ),
    ]
