# Generated by Django 6.0.4 on 2026-04-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='objective',
        ),
        migrations.CreateModel(
            name='PlatformPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Meu Negócio')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('caption', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('approved_text', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_posts', to='posts.socialpost')),
            ],
            options={
                'verbose_name': 'Post por plataforma',
                'verbose_name_plural': 'Posts por plataforma',
                'ordering': ['platform'],
                'unique_together': {('social_post', 'platform')},
            },
        ),
    ]
