# Generated by Django 6.0.4 on 2026-05-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('posts', '0002_remove_socialpost_objective_platformpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='main_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='media_library.mediaasset'),
        ),
    ]
