# Generated by Django 6.0.4 on 2026-05-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_mediaasset_public_url'),
        ('posts', '0003_socialpost_main_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='media_library.mediaasset')),
                ('social_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='posts.socialpost')),
            ],
            options={
                'verbose_name': 'Mídia do post',
                'verbose_name_plural': 'Mídias do post',
                'ordering': ['order', 'id'],
                'unique_together': {('social_post', 'media_asset')},
            },
        ),
    ]
