# Generated by Django 6.0.4 on 2026-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='post_type',
            field=models.CharField(choices=[('single_image', 'Foto única'), ('carousel', 'Carrossel'), ('video', 'Vídeo')], default='carousel', max_length=20),
        ),
    ]
