# Generated by Django 6.0.4 on 2026-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('google_business', 'Google Meu Negócio')], max_length=40)),
                ('account_name', models.CharField(max_length=160)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('scopes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('connected', 'Conectada'), ('disconnected', 'Desconectada'), ('expired', 'Token expirado'), ('error', 'Erro')], default='disconnected', max_length=30)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta social',
                'verbose_name_plural': 'Contas sociais',
                'ordering': ['platform', 'account_name'],
            },
        ),
    ]
