# Generated by Django 6.0.4 on 2026-04-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_remove_socialpost_objective_platformpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Aguardando revisão'), ('approved', 'Aprovado'), ('rejected', 'Reprovado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='posts.socialpost')),
            ],
            options={
                'verbose_name': 'Revisão',
                'verbose_name_plural': 'Revisões',
            },
        ),
    ]
