# Generated by Django 6.0.4 on 2026-05-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('social_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationtarget',
            name='social_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_targets', to='social_accounts.socialaccount'),
        ),
    ]
