# Generated by Django 6.0.4 on 2026-04-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('version', models.CharField(blank=True, max_length=160)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('doors', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=80)),
                ('fuel', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('hatch', 'Hatch'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Picape'), ('unknown', 'Não identificado')], default='unknown', max_length=30)),
                ('usage_profile', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('commercial_positioning', models.TextField(blank=True)),
                ('enrichment_source', models.TextField(blank=True)),
                ('normalized_by_ai', models.BooleanField(default=False)),
                ('enrichment_status', models.CharField(default='pending', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
