# Generated by Django 6.0.4 on 2026-04-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=20)),
                ('file', models.FileField(upload_to='vehicle_media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='vehicle_thumbnails/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['-created_at'],
            },
        ),
    ]
