# Generated by Django 6.0.4 on 2026-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='public_url',
            field=models.URLField(blank=True),
        ),
    ]
